### ISSUE TITLE
源码集成到项目中，不混淆的时候正常运行，混淆之后，进入房间崩溃闪退

### ISSUE THREAD

**Issue by suiyuanchen** [AgoraIO-Community/CloudClass-Android#17]
Process: com.up360.parents.android.activity, PID: 1507
    java.lang.ExceptionInInitializerError
        at sSa$a.SGa(SourceFile:218)
        at sSa$a.findPlatform(SourceFile:212)
        at sSa$a.a(SourceFile:169)
        at sSa.<clinit>(SourceFile:170)
        at oQa.<init>(SourceFile:237)
        at oQa$a.build(SourceFile:1069)
        at io.agora.base.network.RetrofitManager.<init>(SourceFile:51)
        at io.agora.base.network.RetrofitManager.instance(SourceFile:58)
        at io.agora.edu.launch.AgoraEduSDK.launch(SourceFile:135)
        at rT.a(SourceFile:162)
        at Pta.handleMessage(SourceFile:833)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6688)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867)
     Caused by: java.lang.IllegalStateException: OkHttpClient::class.java.`package` must not be null
        at vSa.<clinit>(SourceFile:57)
        at sSa$a.SGa(SourceFile:218) 
        at sSa$a.findPlatform(SourceFile:212) 
        at sSa$a.a(SourceFile:169) 
        at sSa.<clinit>(SourceFile:170) 
        at oQa.<init>(SourceFile:237) 
        at oQa$a.build(SourceFile:1069) 
        at io.agora.base.network.RetrofitManager.<init>(SourceFile:51) 
        at io.agora.base.network.RetrofitManager.instance(SourceFile:58) 
        at io.agora.edu.launch.AgoraEduSDK.launch(SourceFile:135) 
        at rT.a(SourceFile:162) 
        at Pta.handleMessage(SourceFile:833) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6688) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867)

**Comment by suiyuanchen** [comment]
> Process: com.up360.parents.android.activity, PID: 1507
> java.lang.ExceptionInInitializerError
> at sSa$a.SGa(SourceFile:218)
> at sSa$a.findPlatform(SourceFile:212)
> at sSa$a.a(SourceFile:169)
> at sSa.(SourceFile:170)
> at oQa.(SourceFile:237)
> at oQa$a.build(SourceFile:1069)
> at io.agora.base.network.RetrofitManager.(SourceFile:51)
> at io.agora.base.network.RetrofitManager.instance(SourceFile:58)
> at io.agora.edu.launch.AgoraEduSDK.launch(SourceFile:135)
> at rT.a(SourceFile:162)
> at Pta.handleMessage(SourceFile:833)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:192)
> at android.app.ActivityThread.main(ActivityThread.java:6688)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867)
> Caused by: java.lang.IllegalStateException: OkHttpClient::class.java.`package` must not be null
> at vSa.(SourceFile:57)
> at sSa$a.SGa(SourceFile:218) 
> at sSa$a.findPlatform(SourceFile:212) 
> at sSa$a.a(SourceFile:169) 
> at sSa.(SourceFile:170) 
> at oQa.(SourceFile:237) 
> at oQa$a.build(SourceFile:1069) 
> at io.agora.base.network.RetrofitManager.(SourceFile:51) 
> at io.agora.base.network.RetrofitManager.instance(SourceFile:58) 
> at io.agora.edu.launch.AgoraEduSDK.launch(SourceFile:135) 
> at rT.a(SourceFile:162) 
> at Pta.handleMessage(SourceFile:833) 
> at android.os.Handler.dispatchMessage(Handler.java:102) 
> at android.os.Looper.loop(Looper.java:192) 
> at android.app.ActivityThread.main(ActivityThread.java:6688) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867)

解决方案
混淆文件proguard-rules.pro中添加
-keep class io.agora.**{*;}
-keep class com.herewhite.sdk**{*;}

#-------------- okhttp3 start-------------
# OkHttp3
# https://github.com/square/okhttp
# okhttp
-keepattributes Signature
-keepattributes *Annotation*
-keep class com.squareup.okhttp.* { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn com.squareup.okhttp.**

# okhttp 3
-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# Okio
-dontwarn com.squareup.**
-dontwarn okio.**
-keep public class org.codehaus.* { *; }
-keep public class java.nio.* { *; }
#----------okhttp end--------------
